name: Build → Push → Deploy

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: IMAGE="${{ secrets.ARTIFACTORY_HOST }}/docker-local/nginx:${{ github.sha }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-image
        run: |
          IMAGE="${{ secrets.ARTIFACTORY_HOST }}/docker-local/nginx:${{ github.sha }}"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.set-image.outputs.image }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_LOCATION }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Update k8s manifest image and deploy
        run: |
          IMAGE="${{ needs.build-and-push.outputs.image }}"
          # Replace the placeholder image in your deployment YAML
          sed -i "s|my-artifactory.example.com/docker-local/nginx:1.0.0|$IMAGE|g" k8s/nginx-deployment.yaml
          kubectl apply -f k8s/nginx-deployment.yaml
