name: Build → Push → Deploy

on:
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-image
        run: |
          IMAGE="${{ secrets.ARTIFACTORY_HOST }}/docker-local/nginx:${{ github.sha }}"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Log in to Artifactory Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ARTIFACTORY_HOST }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.set-image.outputs.image }}
